// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"hexago/internal/application"
	"hexago/internal/infrastructure/controller"
	"hexago/internal/infrastructure/server"
)

// Injectors from wire.go:

func initialize() server.FiberServer {
	healthService := application.NewHealthService()
	healthController := controller.NewHealthController(healthService)
	fiberServer := server.NewFiberServer(healthController)
	return fiberServer
}
